### PR TITLE
[13.0][MIG]rma_repair

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
"Standard" migration + little fix in rma_account

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
cc @ForgeFlow

**Review by AdriaGForgeFlow — COMMENTED** [review]
You should add [OCA/manufacture](https://github.com/OCA/manufacture) to oca_dependencies

**Comment by AaronHForgeFlow** [comment]
Thank you!

**Comment by AaronHForgeFlow** [comment]
#132 was applied

**Review by AdriaGForgeFlow — APPROVED** [review]

**Pull request merged**
