### PR TITLE
[12.0][FIX] bring Lot/Serial,Delivery Address and Invoicing Address when create a repair order

### PR DESCRIPTION
**Pull request by bodedra**
Issue Reference: #75

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Comment by bodedra** [comment]
@aheficent

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Comment by bodedra** [comment]
Thanks @aheficent @lreficent  :+1:

**Pull request merged**
