### PR TITLE
[16][FIX] rma: qty received and shipped in case of multiple step reception/expedition

### PR DESCRIPTION
**Pull request by florian-dacosta**
Remove changes introduced here : https://github.com/ForgeFlow/stock-rma/commit/ff0e4fb2147a8069ffd7c0499d1f3cb79808cb5a

Because since this commit, the selection of the move previously in this method have evolved, so now, it breaks the quantity received/shipped in the case of chained moves intead of fixing it...

@AaronHForgeFlow @DavidJForgeFlow

### CODE REVIEW

**Comment by DavidJForgeFlow** [comment]
Hi @florian-dacosta,
Thanks for the PR! However, can you add some tests to make sure this isn't breaking any feature?

**Comment by florian-dacosta** [comment]
@DavidJForgeFlow 
Sure, I have added a test about qty_received / delivered with multiple steps (chained moves).
The test will fail if you launch on a 16.0 branch. It is fixed in this PR.
Let me know what you think.

**Review by DavidJForgeFlow — APPROVED** [review]
Looks good to me! @AaronHForgeFlow can you check this also please!

**Review by AaronHForgeFlow — APPROVED** [review]
I think this makes sense. Thank you for the tests.

**Pull request merged**
