### PR TITLE
[11.0] MIG: RMA module

### PR DESCRIPTION
**Pull request by bodedra**

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
Please keep commit history

**Comment by bodedra** [comment]
@jbeficent 

It seems this is first commit on 11.0 branch so no commit history will be in it.

Please correct me.

**Comment by JordiBForgeFlow** [comment]
You have to keep the commit history. These are the accepted OCA guidelines

**Comment by bodedra** [comment]
How may I do it ?

**Comment by max3903** [comment]
@jbeficent Can you be more specific? This PR has only one commit for the the migration to v11. The history is preserved:
https://github.com/ursais/stock-rma/commits/bodedra_11.0_mig_rma

**Comment by JordiBForgeFlow** [comment]
Oh, now I see.

**Comment by max3903** [comment]
@bodedra I fixed Travis configuration and tried to fix the tests. Please complete the migration of the tests as well.

**Comment by JordiBForgeFlow** [comment]
@bodedra I have sent you PR https://github.com/ursais/stock-rma/pull/1 that fixes the errors.

**Comment by max3903** [comment]
:+1:

**Pull request merged**
