### PR TITLE
[17.0][MIG] rma

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Migration of base rma module. 

Supersedes https://github.com/ForgeFlow/stock-rma/pull/502

Reasons for  supersede:

-  Merge 17.0 was broken after merging and reverting by mistake some pull requests https://github.com/ForgeFlow/stock-rma/pull/483 & https://github.com/ForgeFlow/stock-rma/pull/500
-  History was incorrect showing merge commits within it. 
-  Merge conflicts when trying to manually merge other PRs on top on that one.
- Unable to see the changes in the migration commit, making hard for the reviewer to review the code

Sorry for the inconvenience.

@ForgeFlow

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
Tested:

rma group and operate with it
rma lines with multiple route configuration
lot management

**Comment by AaronHForgeFlow** [comment]
Includes also https://github.com/ForgeFlow/stock-rma/pull/492/

**Comment by DavidJForgeFlow** [comment]
Hi Aaron, can you also include #498 ?

**Comment by AaronHForgeFlow** [comment]
@DavidJForgeFlow done. thanks

**Comment by AaronHForgeFlow** [comment]
Also included https://github.com/ForgeFlow/stock-rma/pull/474/

**Review by DavidJForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
I think this is ready to be merged. If some issues arises we can take care of them in future PRs.

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Comment by AaronHForgeFlow** [comment]
I think it is time to merge this, further corrections will be done in future PRs.

**Pull request merged**
