### PR TITLE
[12.0][FIX] fix empty parter on rma picking

### PR DESCRIPTION
**Pull request by dkubiak789**

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
The same error in v.14 with more than 1 step in the pickings. @JordiBForgeFlow

**Comment by JordiBForgeFlow** [comment]
@DavidJForgeFlow Can you forward port to 13,14,15,16?

**Comment by ValentinVinagre** [comment]
> 

THANKS 😄

**Comment by JordiBForgeFlow** [comment]
Fix to 14.0 https://github.com/ForgeFlow/stock-rma/pull/333

**Comment by DavidJForgeFlow** [comment]
Done in all versions left (13.0, 15.0)!

**Pull request merged**
