### PR TITLE
[14][FIX] count produced products going to customer as out pickings

### PR DESCRIPTION
**Pull request by florian-dacosta**
Fix the case where you produce a product and then send it to the customer. It should count as an outgoing picking in that case.

@LoisRForgeFlow @JordiBForgeFlow

### CODE REVIEW

**Comment by florian-dacosta** [comment]
Hello @LoisRForgeFlow @JordiBForgeFlow 
Any chance to have a review on this one ?

**Comment by JordiBForgeFlow** [comment]
@DavidJForgeFlow @AaronHForgeFlow can you check?

**Review by DavidJForgeFlow — APPROVED** [review]
Functional review :+1:

**Comment by florian-dacosta** [comment]
@AaronHForgeFlow Could you check also se we can get it merged if you are ok too?
I would port that to v15 and 16 then.

**Review by AaronHForgeFlow — APPROVED** [review]
Ok for me!

**Pull request merged**
