### PR TITLE
[FIX] TypeError: unhashable type: 'list'

### PR DESCRIPTION
**Pull request by bodedra**
Review:
-----------

https://github.com/Eficent/stock-rma/pull/31#issuecomment-400986745

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Hi @bodedra. Thank you for the fix. Can you create the PR directly to 11.0 instead of that branch? Thanks

**Comment by bodedra** [comment]
@aheficent Submit PR https://github.com/Eficent/stock-rma/pull/39 as per your suggestion.

**Comment by AaronHForgeFlow** [comment]
@bodedra Are you using branch bodedra_11.0_mig_rma here in Eficent repo? It seems to me that nobody is using it, and there is not any PR from that branch.

**Comment by bodedra** [comment]
@aheficent nope. I am not use it. I am not sure. May be @jbeficent use it for some fixes or improvements.

**Comment by AaronHForgeFlow** [comment]
@bodedra @max3903 It seems that branch is the same to the branch 11.0-stock_rma-fixes_28. Both branches are 5 commits ahead 11.0. Are those changes going to be proposed to 11.0?

**Pull request closed without merging**
