### PR TITLE
[14.0][FIX] rma_account: reconcile GDNI when receiving but refund is not expected

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Tries to fix:
https://github.com/ForgeFlow/stock-rma/issues/356

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
Perhaps the refund wizard should have boolean 'free of charge'.

Then, in the operation you could define that an automated refund, should be created after recepit, for the quantities received. In the operation I would distinguish two booleans:
- Automated refund
- Free of charge refund

**Comment by AaronHForgeFlow** [comment]
Well, I have included the two booleans, but basically, the refund_free_of_charge boolean will always be True when the user marks the bollean "automated_refund". I am not sure if that is going to be used in any other sceneraio, but it is there just in case.

**Review by JuanyDForgeflow — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
@AaronHForgeFlow could you forward port this?

**Comment by LoisRForgeFlow** [comment]
ping @AaronHForgeFlow

**Pull request merged**
