### PR TITLE
[14.0][IMP] rma: rma groups improvements (add description, clean views, add lots to reports)

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
See commit messages for details.

@ForgeFlow

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
LGTM! Just one thing,  I couldn't pass the description from the RMA group to the RMA line. Not sure if  I am doing anything wrong:

rma_359

**Comment by LoisRForgeFlow** [comment]
@AaronHForgeFlow Use the "add from serial" or "add from stock move" wizards

**Review by AaronHForgeFlow — APPROVED** [review]
@LoisRForgeFlow  I see. That works good! I would just remove the editable option in the rma lines

**Comment by LoisRForgeFlow** [comment]
@AaronHForgeFlow I agree, I just did. I will merge as soon as the CI is green.

**Pull request merged**
