### PR TITLE
[16.0][FIX] rma: _check_move_partner compare with RMA commercial partner 

### PR DESCRIPTION
**Pull request by AlexPForgeFlow**
When an origin move is selected in an RMA, make the check if the picking address is equal to the delivery address from the RMA customer, instead of the customer address.

### CODE REVIEW

**Review by LoisRForgeFlow — COMMENTED** [review]
Makes sense, but maybe it is too restrictive? maybe checking the commercial partner would be enough and do not block cases in which you will deliver to a different location?

**Comment by AlexPForgeFlow** [comment]
> Makes sense, but maybe it is too restrictive? maybe checking the commercial partner would be enough and do not block cases in which you will deliver to a different location?

Yes, you are right. I didn't think about the case of delivering in different addesses.

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM!

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Perfect! I think we can merge this

**Pull request merged**
