### PR TITLE
[11.0] MIG: rma_account

### PR DESCRIPTION
**Pull request by bodedra**

### CODE REVIEW

**Comment by max3903** [comment]
- [x] Depends on #28

**Comment by bodedra** [comment]
@max3903 @jbeficent 

How may I set `rma_purchase` module as depends of `rma` module 11.0 ?

**Comment by max3903** [comment]
@jbeficent Let us know if you expect any changes. Thanks.

**Comment by AaronHForgeFlow** [comment]
Thank you for the migration!
Is it possible to include here some of the features added in v10 for the rma_account? @max3903 

RMA ACCOUNT

filtering invoices by product: 4f01231
demo data: cab4cf9 and 2103ea0
accountants menu with filter: 4a0a3b3 and d3309cc
create refund from the refund menu by adding rma lines: a107228
nicer name_get to make easier search: d8e068a

**Comment by jgrandguillaume** [comment]
Hi @aheficent ,

It would be really nice that you first accept this work and merge it before asking to include also other. It has taken us quite some time to migrate all this, plus we also took the time to test this all.

Including now other commit in there might get through a whole testing phase again. So it'll be really appreciated that you include this first and raise an issue for the remaining work to do.

Thanks for your consideration,

Joël

**Comment by AaronHForgeFlow** [comment]
@jgrandguillaume Ok, that's sounds fair

**Comment by AaronHForgeFlow** [comment]
I've tested and this is working fine, great work. It works the same as versions 9.0.1.0.0 and 10.0.1.0.0.

Currently version 9.0.2.0.0 and 10.0.2.0.0 are in another branch they are about being merged so versions 9.0.1.0.0 and 10.0.1.0.0 will be over.

Merging this will mean to have separate versions of the RMA, which is costly to maintain.

What do you think @jbeficent @lreficent ?

**Comment by leemannd** [comment]
@aheficent Hello, do you have news about it?

**Comment by AaronHForgeFlow** [comment]
From my point of view this is working as it should (11.0.1.0.0).

After some discussion we prefer in this case not to merge changes until all versions meet. It's very costly to maintain support to different versions. In addition, this can be merged in any other fork of this repo  and keep the development in a separate branch.

**Comment by max3903** [comment]
@aheficent Why not pushing it to the OCA to share the maintenance cost?

**Comment by janbec** [comment]
@aheficent Thanks for the info.
I am looking into starting using your rma app and although I have been looking at the changes in 0.2, I am still wondering if we would face big issues moving from 11.0.1 to a possible 11.0.2
Could you please shortly share your thoughts on this?
Thanks! (And thanks a lot for the great work on this module!)

**Comment by AaronHForgeFlow** [comment]
@max3903 We have not proposed it to OCA to respect the existing design, the current OCA/RMA repo, not migrated to 10.0 though...

@janbec Mostly they are usability improvements, like seeing the invoice number when searching when filling the invoice line or adding filters and menus for the different users. For example, there's a menu with a filter in accounting that gives the accountant the RMAs pending to refund.

However, some others involve changes in the workflow, for example:
- searching first by product and then by invoice line/sale order line (including filtering by that product)
- adding a PO policy and allow to buy. (now the only possibility is to add the route buy as rma_selectable)
- allow to create supplier RMA form any customer RMA, even when it is not a dropship the company may want to return the product to the original supplier.
- Add a setting to decide if using RMA groups or not.

Currently, moving the data will not be too difficult, but it may be in the future if we add more versions.

Regards

**Comment by max3903** [comment]
@aheficent That's my point. There may be a reason why it has not been migrated in the OCA and there is many different people here...

**Comment by max3903** [comment]
@aheficent Can you merge this and port the changes in another pull request later?

**Comment by JordiBForgeFlow** [comment]
@max3903 We need to maintain a structured roadmap, and we are currently leading the repo. @aheficent has clearly stated what changes need to be added in https://github.com/Eficent/stock-rma/issues/37. And this PR is not containing them. I suggest that your team take some time to review and port the changes, and then we can: 1) merge them and 2) propose a PR to OCA.

Once the repo is in OCA I insist that we'll need to maintain the module maintainable, and there needs to be a clear leadership from the maintainers. We cannot just accept the policy of first come first served.

**Comment by max3903** [comment]
@jbeficent It's also the responsibility of the maintainer to publish the roadmap in time. There is nothing more frustrating than notifying 6 months ago that we will migrate some modules (#29) and being told now to comply to a roadmap that was published 22 days ago (#37). Just saying.

@bodedra Can you include the requested changes mentioned in #37 in this pull request and in #31?

**Comment by JordiBForgeFlow** [comment]
@max3903 I understand your fustration, but we need to work on this until it is stable. Sometimes you nail it down the first time you implement something, and sometimes, like this one, it takes some iterations. See, in the end we'll have a much better result. So we need to walk this extra last mile. We also review your changes, and improve when new good features are proposed.

**Comment by AaronHForgeFlow** [comment]
Hi @bodedra  What's the correct rma_purchase version? the one in this PR or this one ?https://github.com/Eficent/stock-rma/pull/31 I'm trying to review but got conflicts. Thanks.

**Comment by bodedra** [comment]
@aheficent rma_purchase version is 11.0

2 days ago I do cherry pick comment from #37 and apply to 11.0 branch. And then do rebase. 

I think I should do cherry pick commit on #31 branch only rather to 11.0. correct ?

**Comment by AaronHForgeFlow** [comment]
Thus, version 11.0.2.0.0 here includes all the changes of version 11.0.1.0.0, right?

**Comment by bodedra** [comment]
Nope. I mixed up branch here when do cherry pick. Let me revert back it and update you.

**Comment by AaronHForgeFlow** [comment]
Ok! Please let me know. Thank you!

**Comment by max3903** [comment]
@aheficent I think it's ready to be merged, right?

Thanks @bodedra!

**Comment by AaronHForgeFlow** [comment]
@max3903 I'm reviewing it

**Comment by AaronHForgeFlow** [comment]
Can you check the refunds navigation button? It's showing errors when no refund was created:
image

`TypeError: unhashable type: 'list'`

**Comment by max3903** [comment]
Ping @bodedra

**Comment by bodedra** [comment]
@aheficent Please review it. We fix that issues.

CC @max3903

**Comment by AaronHForgeFlow** [comment]
Hi @bodedra Good job. Just a couple of things pending:
The menus in Invoicing called **Customer RMA to refund** and **Supplier RMA to refund** must include the proper filters, only rma lines to refund should appear. Please check commit: https://github.com/Eficent/stock-rma/commit/4a0a3b361e8ace8925386b269cb91db94797fd3a
image

Can you include the feature to create vendor invoice lines by selecting rma order line in vendor's invoice view? If you go to Invoicing > Vendor Bills and create one, you will see there's a field called "add Purchase Order":
image
 By selecting a Purchase order the system will create invoice lines accordingly. We did the same there from rma_lines, so we can create invoice lines directly by selecting rma lines. Please check commit: https://github.com/Eficent/stock-rma/commit/a107228b04339e62d1fe45cd14b7914c1e4386bb

And the last thing. Now it's too difficult to search by invoices because only the product appears:
image

Can you improve the name get as we did in this commit? https://github.com/Eficent/stock-rma/commit/d8e068a047ee13e650b26a10336599a76ed018bb

After including all this  I'll merge this one. Please let me know if you have trouble, I'll help you to introduce the changes. Perhaps doing cherry-picks of the mentioned commits is enough, but I have not tried.

On the other hand, I will create a PR to include all the latest changes done in previous versions in rma module. I'll ping you all so you can comment.

Regards

**Comment by bodedra** [comment]
@aheficent As per your 3 suggested commits are already in. Please review it.

Your commit  ----------->   Related commit in 11.0

https://github.com/Eficent/stock-rma/commit/4a0a3b361e8ace8925386b269cb91db94797fd3a           ----------->           https://github.com/Eficent/stock-rma/pull/30/files#diff-d063dd1188bfc42cd82df55d1ecb7822

https://github.com/Eficent/stock-rma/commit/a107228b04339e62d1fe45cd14b7914c1e4386bb      ----------->          https://github.com/Eficent/stock-rma/pull/30/files#diff-7396d4c612cd6a263feb11156b80ced6

https://github.com/Eficent/stock-rma/commit/d8e068a047ee13e650b26a10336599a76ed018bb      ----------->      https://github.com/Eficent/stock-rma/pull/30/files#diff-7396d4c612cd6a263feb11156b80ced6R128

CC @max3903

**Comment by AaronHForgeFlow** [comment]
@bodedra The commits are in but the feature is not there, I did functional checks and the feature is not there. Either the code was overwritten in a later commit or the code is not working in v11 so we have to fix that. I'll try to identify why is not working.

**Comment by bodedra** [comment]
@aheficent there is a issue on view side. If you remove attrs then it will display. I am on it. Will update you.

**Comment by AaronHForgeFlow** [comment]
ok! I'l trying to include the latest changes in rma base module here: https://github.com/Eficent/stock-rma/tree/11.0-v2 I'll create the PR as soon as it works.

Thanks.

**Comment by bodedra** [comment]
@aheficent all issues are resolve. Please review it.

CC @max3903

**Comment by AaronHForgeFlow** [comment]
@bodedra Nice! Everything work now. Thank you!

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:  @bodedra Nice! Everything work now. Thank you!

**Comment by AaronHForgeFlow** [comment]
I closed this by mistake. Checks were green so merging.

**Comment by bodedra** [comment]
Appreciate your supports. Thank you @aheficent @max3903

**Comment by max3903** [comment]
@aheficent @bodedra Great team work! Thank you.

**Pull request merged**
