### PR TITLE
[14.0][ADD] Mass action for request approval RMA order line

### PR DESCRIPTION
**Pull request by ChrisOForgeFlow**
Related to #217 

Testing current behavior was fixed on #219

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@ChrisOForgeFlow can you port to v13 and v15?

**Comment by ChrisOForgeFlow** [comment]
> @ChrisOForgeFlow can you port to v13 and v15?

Currently done

**Comment by LoisRForgeFlow** [comment]
@ChrisOForgeFlow maybe I'm blind but... I cannot find the PRs of the ports, can you point them to me?

**Comment by ChrisOForgeFlow** [comment]
> @ChrisOForgeFlow maybe I'm blind but... I cannot find the PRs of the ports, can you point them to me?

Sorry, in those branches I commit directly

https://github.com/ForgeFlow/stock-rma/commit/2d3cbd05ae47d0ae996547aa8941dc91320ae9d8
https://github.com/ForgeFlow/stock-rma/commit/da1b0a4dad1b817e8215307c6bc1c69b7f8ea89f

**Pull request merged**
