### PR TITLE
[16][FIX] rma: make date_rma stored once again on rma_order

### PR DESCRIPTION
**Pull request by florian-dacosta**
It became unstored in this PR https://github.com/ForgeFlow/stock-rma/pull/443
But I think it was not intentional since there is an index, a default... The description of the compute method says we want to keep its own value if date of the lines have a different date, which is not possible if the field is not stored.
Also, the field is in the "group by" view and fail, because we can't group by this not stored field.

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
I agree with you

**Comment by AaronHForgeFlow** [comment]
@DavidJForgeFlow @LoisRForgeFlow

**Review by LoisRForgeFlow — APPROVED** [review]
Yes, I also agree :+1:

**Comment by LoisRForgeFlow** [comment]
@AaronHForgeFlow merge and port at your convenience

**Pull request merged**
