### PR TITLE
[16.0][IMP] rma: add date to rma_order_line

### PR DESCRIPTION
**Pull request by AlexPForgeFlow**
Forward port of #432

### CODE REVIEW

**Review by DavidJForgeFlow — APPROVED** [review]
LGTM!

**Review by BernatPForgeFlow — APPROVED** [review]
LGTM!

**Review by mariadforgeflow — APPROVED** [review]
LGTM! Code review.

**Comment by AaronHForgeFlow** [comment]
Hi @AlexPForgeFlow @DavidJForgeFlow as long the rma_date is in the rma group I think it has to be consistent with the date in the lnies. Also added the fields in the rma line views

**Pull request merged**
