### PR TITLE
[10.0]RMA improvement

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
review round, includes fixes here: #33

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Includes changes here #36

**Comment by AaronHForgeFlow** [comment]
Merging this to 10.0 as soon as all checks passed and dependencies merged in OCA

**Comment by AaronHForgeFlow** [comment]
Green now. Merging as soon as OCA dependencies are merged in OCA.

**Comment by AaronHForgeFlow** [comment]
All changes here are applied to v11 and v12 so will merge as soon as purchase_analytic is merged in OCA

**Comment by AaronHForgeFlow** [comment]
Also fixes #86

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

Ready to merge :)

**Comment by AaronHForgeFlow** [comment]
@MiquelRForgeFlow Ok, but please keep the branch 10.0-imp-rma

**Pull request merged**
