### PR TITLE
[FIX] TypeError: unhashable type: 'list'

### PR DESCRIPTION
**Pull request by bodedra**
Review:
-----------

https://github.com/Eficent/stock-rma/pull/31#issuecomment-400986745

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Hi @bodedra I'm still getting an error when putting the route "Buy" in incoming shipments. But anyway you can ignore that. As we are including a purchase policy in rma _purchase module we can consider the route buy as a configuration error in a implementation. We can merge this as is not affecting the normal behavior and this is preventing to get an error when no shipment is created in the wizards. Thanks

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Comment by bodedra** [comment]
@aheficent yes I am agree with you. When we create incoming shipment with Buy. Odoo creates a purchase order. And our code try to fetch view of incoming picking. That's lead error.

In this case, do we want to create incoming shipment or redirect to purchase order form or any new way?

**Comment by AaronHForgeFlow** [comment]
@bodedra for now, let's consider it a configuration error, so let's keep it like that. As users con create PO directly from a specific button, it makes not much sense to create those form an incoming shipment.

Regards.

**Comment by AaronHForgeFlow** [comment]
@bodedra actually, I was wrong.

The module that check if there's a purchase order related to the rma is the rma always. The thing is, the recommended way to create purchase order from the rma is by using the custom wizard.

However, if the user selects a buy route and create incoming shipment, then the button should return the purchase order, that is the current behavior  in v10. The code that is supposed to do that is the following:
https://github.com/ursais/stock-rma/blob/7e2724118e0c63d43d0fe61287aa503571339bdd/rma_purchase/wizards/rma_make_picking.py#L20

But for some reason is not working in v11. I'll take a further look at it and try to fix it. To fix it we can use this PR https://github.com/Eficent/stock-rma/pull/31 because this is code of the rma_purchase

**Pull request merged**
