### PR TITLE
[IMP] Update pre-commit lints according with OCA ones

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
@AaronHForgeFlow at some point we should do that :)

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
@HviorForgeFlow this is gonna hurt :smile:

**Comment by AaronHForgeFlow** [comment]
unbelievable :thinking:

**Comment by HviorForgeFlow** [comment]
The problem is not here, will be on future migration PRs coming from previous versions :)

**Comment by AaronHForgeFlow** [comment]
:) Then feel free to hit the button

**Comment by AaronHForgeFlow** [comment]
Seems this need rebase now. strange. Will do later.

**Comment by AaronHForgeFlow** [comment]
> Seems this need rebase now. strange. Will do later.

Sorry, it was my fault. I did the merge for #133 I think now it is fixed

**Pull request merged**
