### PR TITLE
[16.0][ADD] rma_repair_put_away: glue module between rma_repair & rma_put_away

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
When not using rma_put_away you can define push rules anyway to move the products to the repair location, and those transfers count as rma repair transfers

If you install and use rma_put_away then the rma repair transfers are the ones from the putaway moves

Before this commit there is a dependency issue because the rma_repair code is using a field declared in the rma_put_away, this commit fixes that issue.

### CODE REVIEW

**Review by JordiMForgeFlow — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
~~Why not making PR to OCA?~~

**Comment by AaronHForgeFlow** [comment]
@ChrisOForgeFlow do you think this is fine?

**Comment by ChrisOForgeFlow** [comment]
> @ChrisOForgeFlow do you think this is fine?

Yes, thank you

**Review by ChrisOForgeFlow — APPROVED** [review]
> @ChrisOForgeFlow do you think this is fine?

Yes, thank you

**Comment by AaronHForgeFlow** [comment]
@ChrisOForgeFlow thank you. I will add a test and merge it.

**Pull request merged**
