### PR TITLE
[13.0][MIG] rma_purchase

### PR DESCRIPTION
**Pull request by Chanakya-SerpentCS**

### CODE REVIEW

**Comment by Chanakya-SerpentCS** [comment]
@bodedra  Migration is done and precommit is also done by me but here it's not working can you please check. Precommit configuration.

**Comment by bodedra** [comment]
@AaronHForgeFlow @LoisRForgeFlow Is that something you can help here?

**Comment by AaronHForgeFlow** [comment]
Will fix pre-commit config soon. Thanks.

**Comment by bodedra** [comment]
Much appreciate @AaronHForgeFlow

**Comment by AaronHForgeFlow** [comment]
Hi @Chanakya-SerpentCS. Base branch is fixed now :) and you will need to rebase your branch.

Just do:
git remote update
git rebase origin/13.0
#### Fix the conflicts in rma_repair, that module changed because of the pre-commit, nothing important

Then you will need to run the pre-commit again:

pre-commit run -a

Then you should be able to commit the results and then you will have to do git push force as long as you did the rebase. Just let me know if that does not work or if you have a better way to do this.

Regards.

**Comment by Chanakya-SerpentCS** [comment]
@AaronHForgeFlow  Thanks.

@bodedra  over to you now.

**Review by AaronHForgeFlow — APPROVED** [review]
@Chanakya-SerpentCS  so far so good:

Create an RMA from originating PO line.
Use of the purchase policy seems correct.
The creation of the quotation from the RMA seems also correct.
Qty purchases updated correctly.

**Comment by AaronHForgeFlow** [comment]
Seems there is an issue when creating delivery orders to the vendor, but seems unrelated to this pull request.

**Pull request merged**
