### PR TITLE
[11.0] MIG: rma_purchase

### PR DESCRIPTION
**Pull request by bodedra**

### CODE REVIEW

**Comment by max3903** [comment]
Depends on:

- [x] #30

**Comment by AaronHForgeFlow** [comment]
Thank you for the migration:

Code seems ok to me. Is it possible to include here some of the improvements done lately in v9 and v10? @max3903 

RMA PURCHASE
name get method when searching: 89a2f5c
add purchase policy and create Purchases from the RMA (it is needed for advance refund operations): 2100329

Regards.

**Comment by jgrandguillaume** [comment]
Hi @aheficent ,

It would be really nice that you first accept this work and merge it before asking to include also other. It has taken us quite some time to migrate all this, plus we also took the time to test this all.

Including now other commit in there might get through a whole testing phase again. So it'll be really appreciated that you include this first and raise an issue for the remaining work to do.

Thanks for your consideration,

Joël

**Comment by AaronHForgeFlow** [comment]
@jgrandguillaume ok deal, I'll do a functional review

**Comment by AaronHForgeFlow** [comment]
I'm getting error when creating incoming shipment and using the route buy. I thought it was in the method `get_action` that returns the picking view but it is not getting there:

The full trace:

> Error:
Odoo Server Error
Traceback (most recent call last):
  File "/home/ahenriquez/PycharmProjects/odoo11/OCB/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/ahenriquez/PycharmProjects/odoo11/OCB/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/ahenriquez/PycharmProjects/odoo11/OCB/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/ahenriquez/PycharmProjects/odoo11/OCB/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/home/ahenriquez/PycharmProjects/odoo11/OCB/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/ahenriquez/PycharmProjects/odoo11/OCB/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/ahenriquez/PycharmProjects/odoo11/OCB/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/ahenriquez/PycharmProjects/odoo11/OCB/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/ahenriquez/PycharmProjects/odoo11/OCB/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/ahenriquez/PycharmProjects/odoo11/OCB/addons/web/controllers/main.py", line 931, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/ahenriquez/PycharmProjects/odoo11/OCB/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/ahenriquez/PycharmProjects/odoo11/OCB/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/ahenriquez/PycharmProjects/odoo11/OCB/odoo/api.py", line 678, in call_kw_multi
    recs = self.with_context(context or {}).browse(ids)
  File "/home/ahenriquez/PycharmProjects/odoo11/OCB/odoo/models.py", line 4334, in browse
    return self._browse(ids, self.env, prefetch)
  File "/home/ahenriquez/PycharmProjects/odoo11/OCB/odoo/models.py", line 4321, in _browse
    prefetch[cls._name].update(ids)
TypeError: unhashable type: 'list'

You can consider it as configuration mistake and don't let users to out the route buy as rma_selectable.

Anyway, in v9.0.2.0.0 and v10.0.2.0.0 rma_purchase adds a wizard to create the PO directly without adding the route buy as rma_selectable. 

Regards.

**Comment by leemannd** [comment]
@bodedra Hello, did you check the latests comment?

**Comment by max3903** [comment]
Ping @bodedra

**Comment by bodedra** [comment]
@aheficent May you provide me steps to reproduce it same as well as product configuration ?

**Comment by AaronHForgeFlow** [comment]
@bodedra  Go to routes and set **buy** as rma_selectable. Then create a supplier RMA and put **buy** as in_route. Then approve the RMA and create an incoming shipment.

**Comment by bodedra** [comment]
@aheficent Thanks for your quick response. We will update you tomorrow on it.

**Comment by AaronHForgeFlow** [comment]
@bodedra thanks to you.

Buying is used for many companies as RMA policy. So imagine you buy a product and you want to return it. Then, the vendor tells you: "ok, I authorize you to return the part and I'll give you a full refund for this product, but you have to buy the same part".

However selecting route buy as in_route is not very intuitive. That's why we added a purchase policy in versions 10.0.2.0.0 and 9.0.2.0.0

**Comment by bodedra** [comment]
@aheficent https://github.com/Eficent/stock-rma/pull/38 will take care of it.

**Comment by bodedra** [comment]
@aheficent Ignore https://github.com/Eficent/stock-rma/pull/38 and review https://github.com/Eficent/stock-rma/pull/39 for reported error.

**Comment by bodedra** [comment]
@aheficent Please review these PR. We do cheery pick as per your suggestion at https://github.com/Eficent/stock-rma/issues/37 and migrate/improve to 11.0

CC @max3903

**Comment by AaronHForgeFlow** [comment]
Sure @bodedra I'll review and I'll come back to you. Thanks

**Comment by max3903** [comment]
@bodedra I did the rebase. I will leave the fixing up to you.

**Comment by bodedra** [comment]
:green_apple:

Ping @aheficent @max3903

**Review by max3903 — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Hi @bodedra, nice work.

The name_get method in the purchase order lines is not working, only the product appears:
image

Can you include the PO number and the quantity? This commit is supposed to do that but it's not working: https://github.com/Eficent/stock-rma/commit/89a2f5cbb3a4def52644b3cc59d09c0d84dc0100
Please see how it looks in v10:

image

**Comment by AaronHForgeFlow** [comment]
Another more important thing. When creating the PO from the button, the PO that pops up should be filled with the product and the quantity required. Now only the supplier is filled:
image

Can you please check the purchase order file of this commit: https://github.com/Eficent/stock-rma/commit/2100329188e45bf465d43b47c7e45cdb5041bc11 ?

Thank you!

**Comment by AaronHForgeFlow** [comment]
The rest is working fine IMO. Nice work!  I'll try to propose the v11.0.2.0.0 as soon as possible

**Comment by bodedra** [comment]
@aheficent I fixed issue of name_get in Originating Purchase Line.

And I can not reproduce as you described https://github.com/Eficent/stock-rma/pull/31#issuecomment-408145536 

Here is code reference.

We pass context in button "Create Purchase Order" at https://github.com/Eficent/stock-rma/pull/31/files#diff-564b110dc2cdcdc413c62d75e63c1ebdR20 and get context value at https://github.com/Eficent/stock-rma/pull/31/files#diff-b8fb35db624e5b04d5aab2981ce5a523R14

Would you please review it again ?

CC @max3903

**Comment by AaronHForgeFlow** [comment]
Ok, I'll review it again. As we don't have runbot here I have to test in local.

**Comment by AaronHForgeFlow** [comment]
@bodedra I tested again and it's still the same. The code seems correct  tough. Is the purchase order line filled with the values of the rma_line for you?

**Comment by bodedra** [comment]
@aheficent yes, it filled with rma_line.

**Comment by bodedra** [comment]
May we do screen share via hangout ?

**Comment by AaronHForgeFlow** [comment]
Sure.

**Comment by bodedra** [comment]
Can you share your email address ? or connect me at "bodedra@ursainfosystems.com"

**Comment by AaronHForgeFlow** [comment]
I sent to you an invitation. ahenriquez@eficent.com

**Comment by AaronHForgeFlow** [comment]
Nice to meet you @bodedra  I'll try the rma with enterprise code and I'll come back to you.

**Comment by AaronHForgeFlow** [comment]
Checked. In community version there's a specific method that invalidates the changes in the `new `method. So I'll take a different approach here and I'll create the PO from an intermediate wizard. An intermediate wizard is used in rma_sale so it'll be more consistent with that module and that way it'll work for both community and enterprise. I'll will propose the changes to your branch.

**Comment by bodedra** [comment]
Me too. Nice to meet you. Thanks for your time. @aheficent

**Comment by AaronHForgeFlow** [comment]
@bodedra  Thank you for the fix!

**Comment by bodedra** [comment]
@aheficent one question: When we create Purchase order from wizard, Should we allow to choose any supplier or only link with Supplier RMA ?

**Comment by AaronHForgeFlow** [comment]
Good point. Yes, I think we can put a domain there, the supplier should be the same.

**Comment by bodedra** [comment]
Okay. I will improve it.

**Comment by bodedra** [comment]
@aheficent readonly will work. I have tested it and work fine. Please review it.

**Comment by bodedra** [comment]
:green_apple:

@aheficent @max3903

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Good!

**Comment by AaronHForgeFlow** [comment]
Just one thing, there are changes in this PR for rma module and the changes shown are already in 11.0 branch. I'm checking.

**Comment by AaronHForgeFlow** [comment]
Yes, those 3 commits are already merged in 11.0, we should exclude those from this PR:

image

**Comment by bodedra** [comment]
Thanks for providing details. We will revert back those commit.

**Comment by bodedra** [comment]
@aheficent Can you check it again ?

**Comment by AaronHForgeFlow** [comment]
There's still a change in the rma module :crying_cat_face:

**Comment by MiquelRForgeFlow** [comment]
@bodedra You should do a 'rebase' from 11.0 branch instead of doing this "reverts" commits...

```
git fetch origin 11.0
git rebase -i origin/11.0
```

and in the rebase you should drop the "revert" commits

**Comment by bodedra** [comment]
@mreficent rebase it with 11.0

**Comment by MiquelRForgeFlow** [comment]
ok, now delete the "revert" commits

**Comment by AaronHForgeFlow** [comment]
I will do the thing and I'll let you know.

**Comment by bodedra** [comment]
@mreficent Thanks for your suggestion. 

@aheficent Please review it. Now "RMA" modules changes are out from this PR.

CC @max3903

**Comment by AaronHForgeFlow** [comment]
@bodedra I seems good now :)  Before merging I will propose to your branch the latests improvements on tests scripts for this module @lreficent did here: 184c8873864f6e9e496d79f5ef72a01eb0d5b953

Done here: https://github.com/ursais/stock-rma/pull/3

**Comment by bodedra** [comment]
Ping @aheficent

**Comment by max3903** [comment]
@aheficent @jbeficent @bodedra Thank you! :+1:

**Pull request merged**
