### PR TITLE
[15.0][MIG] rma_purchase_operating_unit

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
@JasminSForgeFlow can you fix this PR? It seems there are conflicts with another module, could you rebase and fix conflicts?

**Comment by JasminSForgeFlow** [comment]
> @JasminSForgeFlow can you fix this PR? It seems there are conflicts with another module, could you rebase and fix conflicts?

Fixed, Thanks

**Comment by AaronHForgeFlow** [comment]
Github is telling me that there are conflicts in this PR. Can you check you rebase with the latest code?

**Comment by JasminSForgeFlow** [comment]
> Github is telling me that there are conflicts in this PR. Can you check you rebase with the latest code?

I am not sure why there is a conflict even updating it. I have just follow migration process and pushed it so it is up to date now

**Review by AaronHForgeFlow — APPROVED** [review]
It works same as in previous versions.

I miss some features like filling in the OU in the RMA line when selecting a source PO, but that can be done in another PR.

**Pull request merged**
